//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sundew.DiscriminatedUnions.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sundew.DiscriminatedUnions.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch should handle cases of all possible types.
        /// </summary>
        internal static string AllCasesNotHandledDescription {
            get {
                return ResourceManager.GetString("AllCasesNotHandledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; case(s) not handled.
        /// </summary>
        internal static string AllCasesNotHandledMessageFormat {
            get {
                return ResourceManager.GetString("AllCasesNotHandledMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All possible types not handled.
        /// </summary>
        internal static string AllCasesNotHandledTitle {
            get {
                return ResourceManager.GetString("AllCasesNotHandledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A switch on a discriminated union should not handle the default case.
        /// </summary>
        internal static string SwitchShouldNotHaveDefaultCaseDescription {
            get {
                return ResourceManager.GetString("SwitchShouldNotHaveDefaultCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a discriminated union and should not handle the default case.
        /// </summary>
        internal static string SwitchShouldNotHaveDefaultCaseMessageFormat {
            get {
                return ResourceManager.GetString("SwitchShouldNotHaveDefaultCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default case should not be handled.
        /// </summary>
        internal static string SwitchShouldNotHaveDefaultCaseTitle {
            get {
                return ResourceManager.GetString("SwitchShouldNotHaveDefaultCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A switch on a discriminated union should throw DiscriminatedUnionException in default case.
        /// </summary>
        internal static string SwitchShouldThrowInDefaultCaseDescription {
            get {
                return ResourceManager.GetString("SwitchShouldThrowInDefaultCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a discriminated union and should throw DiscriminatedUnionException in default case.
        /// </summary>
        internal static string SwitchShouldThrowInDefaultCaseMessageFormat {
            get {
                return ResourceManager.GetString("SwitchShouldThrowInDefaultCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default case should throw DiscriminatedUnionException.
        /// </summary>
        internal static string SwitchShouldThrowInDefaultCaseTitle {
            get {
                return ResourceManager.GetString("SwitchShouldThrowInDefaultCaseTitle", resourceCulture);
            }
        }
    }
}
