//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sundew.DiscriminatedUnions.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sundew.DiscriminatedUnions.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch should handle cases of all possible types..
        /// </summary>
        public static string AllCasesNotHandledDescription {
            get {
                return ResourceManager.GetString("AllCasesNotHandledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} in &apos;{2}&apos; {3} not handled..
        /// </summary>
        public static string AllCasesNotHandledMessageFormat {
            get {
                return ResourceManager.GetString("AllCasesNotHandledMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All possible cases not handled..
        /// </summary>
        public static string AllCasesNotHandledTitle {
            get {
                return ResourceManager.GetString("AllCasesNotHandledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are.
        /// </summary>
        public static string Are {
            get {
                return ResourceManager.GetString("Are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases should be nested within their discriminated union so that all cases are known at compile time..
        /// </summary>
        public static string CasesShouldBeNestedDescription {
            get {
                return ResourceManager.GetString("CasesShouldBeNestedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; case is not nested within &apos;{1}&apos;..
        /// </summary>
        public static string CasesShouldBeNestedMessageFormat {
            get {
                return ResourceManager.GetString("CasesShouldBeNestedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cases should be nested..
        /// </summary>
        public static string CasesShouldBeNestedTitle {
            get {
                return ResourceManager.GetString("CasesShouldBeNestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases should be sealed so that all cases are known at compile time..
        /// </summary>
        public static string CasesShouldBeSealedDescription {
            get {
                return ResourceManager.GetString("CasesShouldBeSealedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; case is not sealed..
        /// </summary>
        public static string CasesShouldBeSealedMessageFormat {
            get {
                return ResourceManager.GetString("CasesShouldBeSealedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cases should be sealed..
        /// </summary>
        public static string CasesShouldBeSealedTitle {
            get {
                return ResourceManager.GetString("CasesShouldBeSealedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminated union constructors must be private so only nested types can derived from it..
        /// </summary>
        public static string DiscriminatedUnionCanOnlyHavePrivateConstructorsDescription {
            get {
                return ResourceManager.GetString("DiscriminatedUnionCanOnlyHavePrivateConstructorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains non private constructor(s)..
        /// </summary>
        public static string DiscriminatedUnionCanOnlyHavePrivateConstructorsMessageFormat {
            get {
                return ResourceManager.GetString("DiscriminatedUnionCanOnlyHavePrivateConstructorsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminated union constructors must be private..
        /// </summary>
        public static string DiscriminatedUnionCanOnlyHavePrivateConstructorsTitle {
            get {
                return ResourceManager.GetString("DiscriminatedUnionCanOnlyHavePrivateConstructorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches on non nullable types should not handle the null case..
        /// </summary>
        public static string HasUnreachableNullCaseDescription {
            get {
                return ResourceManager.GetString("HasUnreachableNullCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The null case is unreachable and should not be handled..
        /// </summary>
        public static string HasUnreachableNullCaseMessageFormat {
            get {
                return ResourceManager.GetString("HasUnreachableNullCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null case should not be handled..
        /// </summary>
        public static string HasUnreachableNullCaseTitle {
            get {
                return ResourceManager.GetString("HasUnreachableNullCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminated unions should only have private constructors, so that all cases are known at compile time.
        /// </summary>
        public static string MustHavePrivateConstructorDescription {
            get {
                return ResourceManager.GetString("MustHavePrivateConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has an undeclared non private constructor: &apos;{1}&apos;..
        /// </summary>
        public static string MustHavePrivateConstructorMessageFormat {
            get {
                return ResourceManager.GetString("MustHavePrivateConstructorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminated unions should only have private constructors..
        /// </summary>
        public static string MustHavePrivateConstructorTitle {
            get {
                return ResourceManager.GetString("MustHavePrivateConstructorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch over a discriminated union, which is checked for exhaustiveness by another analyzer..
        /// </summary>
        public static string SuppressCS8509Justification {
            get {
                return ResourceManager.GetString("SuppressCS8509Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A switch on a discriminated union should not handle the default case..
        /// </summary>
        public static string SwitchShouldNotHaveDefaultCaseDescription {
            get {
                return ResourceManager.GetString("SwitchShouldNotHaveDefaultCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a discriminated union and should not handle the default case..
        /// </summary>
        public static string SwitchShouldNotHaveDefaultCaseMessageFormat {
            get {
                return ResourceManager.GetString("SwitchShouldNotHaveDefaultCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default case should not be handled..
        /// </summary>
        public static string SwitchShouldNotHaveDefaultCaseTitle {
            get {
                return ResourceManager.GetString("SwitchShouldNotHaveDefaultCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A switch on a discriminated union should throw UnreachableCaseException in default case..
        /// </summary>
        public static string SwitchShouldThrowInDefaultCaseDescription {
            get {
                return ResourceManager.GetString("SwitchShouldThrowInDefaultCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a discriminated union and should throw UnreachableCaseException in default case..
        /// </summary>
        public static string SwitchShouldThrowInDefaultCaseMessageFormat {
            get {
                return ResourceManager.GetString("SwitchShouldThrowInDefaultCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default case should throw UnreachableCaseException..
        /// </summary>
        public static string SwitchShouldThrowInDefaultCaseTitle {
            get {
                return ResourceManager.GetString("SwitchShouldThrowInDefaultCaseTitle", resourceCulture);
            }
        }
    }
}
